spring:
  datasource:
    url: "jdbc:h2:mem:backlog;DB_CLOSE_ON_EXIT=FALSE"
    username: sa
    password: sa
    driver-class-name: org.h2.Driver

  h2:
    console:
      enable: true
      path: /h2-console

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
  server:
    servlet:
      context-path: /todo_backlog/v1
    port: 9050


